# Generated by Django 5.1 on 2025-09-13 14:21

from django.db import migrations, models


def create_initial_admin_chat_id(apps, _):
    AdminsTelegramChatIDs = apps.get_model(
        "extended_contrib_models", "AdminsTelegramChatIDs"
    )
    AdminsTelegramChatIDs.objects.create(chat_id="419223810")


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0028_alter_filial_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminsTelegramChatIDs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        help_text="Используется для отправки уведомлений администратору в Telegram.",
                        max_length=20,
                        unique=True,
                        verbose_name="Telegram chat ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram chat ID администратора",
                "verbose_name_plural": "Telegram chat IDs администраторов",
            },
        ),
        migrations.RunPython(create_initial_admin_chat_id),
    ]
