# Generated by Django 5.1 on 2025-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "extended_contrib_models",
            "0030_extendedsite_parent_organization_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminsTelegramChatIDs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        help_text="Используется для отправки уведомлений администратору в Telegram.",
                        max_length=20,
                        unique=True,
                        verbose_name="Telegram chat ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "TG chat ID администратора",
                "verbose_name_plural": "TG chat IDs администраторов",
            },
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_de",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_en",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_es",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_ru",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_uk",
        ),
    ]
