# Generated by Django 5.1 on 2025-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0029_alter_filial_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminsTelegramChatIDs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        help_text="Используется для отправки уведомлений администратору в Telegram.",
                        max_length=20,
                        unique=True,
                        verbose_name="Telegram chat ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "TG chat ID администратора",
                "verbose_name_plural": "TG chat IDs администраторов",
            },
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="city",
            field=models.CharField(
                default="Globally", max_length=40, verbose_name="Название города"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="city_de",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="city_en",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="city_ru",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="city_uk",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название города"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country",
            field=models.CharField(
                default="Europe", max_length=40, verbose_name="Название страны"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_de",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_en",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_ru",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AddField(
            model_name="extendedsite",
            name="country_uk",
            field=models.CharField(
                max_length=40, null=True, verbose_name="Название страны"
            ),
        ),
    ]
