# Generated by Django 5.1 on 2025-09-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0032_adminstelegramchatids"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminstelegramchatids",
            options={
                "verbose_name": "TG chat ID администратора",
                "verbose_name_plural": "TG chat IDs администраторов",
            },
        ),
    ]
