# Generated by Django 5.1 on 2025-09-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extended_contrib_models", "0033_alter_adminstelegramchatids_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_de",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_el",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_en",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_ru",
        ),
        migrations.RemoveField(
            model_name="extendedsite",
            name="parent_organization_url_uk",
        ),
    ]
